apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: myapp-deploy
  labels:
    app: myapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-pod
        image: vikas9821/my-app-node
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9091
